"use client"
import { Poppins } from 'next/font/google';
import { QueryClient, QueryClientProvider } from 'react-query';
import Modals from '@/components/modals';
import './globals.css';

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['500', '600', '900']
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      retry: false
    },
    mutations: {
      retry: false
    }
  }
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en" >
      <body style={{ height: '3000px' }} className={poppins.className}>
        <QueryClientProvider client={queryClient}>
          { children }
          <Modals />
        </QueryClientProvider>
      </body>
    </html>
  )
}
