import { Poppins } from 'next/font/google';
import Modals from '@/components/modals';
import './globals.css';

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['500', '600', '900']
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={poppins.className}>
      <body style={{ height: '3000px' }}>
        { children }
        <Modals />
      </body>
    </html>
  )
}
